name = "M_draw"
version = "0.1.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John S. Urban"

[library]
source-dir = "src"
build-script = "fpm.mk"

#[[test]]  name="demo_system_putenv"       source-dir="PROGRAMS/putenv"       main="demo_system_putenv.f90"
#[[test]]  name="demo_system_rand"         source-dir="PROGRAMS/rand"         main="demo_system_rand.f90"
#[[test]]  name="demo_system_readdir"      source-dir="PROGRAMS/readdir"      main="demo_system_readdir.f90"
#[[test]]  name="demo_system_readenv"      source-dir="PROGRAMS/readenv"      main="demo_system_readenv.f90"

[[executable]]
name="h2v"
source-dir="PROGRAMS/MAKE_HERSHEY"
main="h2v.c"

[[test]]  name="make_hershey"      source-dir="test/make_hershey"      main="make_hershey.f90"

#[test.dependencies]
#M_msg          = { git = "https://github.com/urbanjost/M_msg.git" }
#M_time         = { git = "https://github.com/urbanjost/M_time.git" }
#M_process      = { git = "https://github.com/urbanjost/M_process.git" }
#M_system      = { git = "https://github.com/urbanjost/M_system.git" }
#M_debug.inc

#M_cli         = { git = "https://github.com/urbanjost/M_cli.git"  }
#M_calculator  = { git = "https://github.com/urbanjost/M_calculator.git" }
#M_change      = { git = "https://github.com/urbanjost/M_change.git" }
#M_color       = { git = "https://github.com/urbanjost/M_color.git" }
#M_history     = { git = "https://github.com/urbanjost/M_history.git" }
#M_io          = { git = "https://github.com/urbanjost/M_io.git" }
#M_strings     = { git = "https://github.com/urbanjost/M_strings.git" }
#M_kracken95   = { git = "https://github.com/urbanjost/M_kracken95.git" }
#M_commandline = { git = "https://github.com/urbanjost/M_commandline.git" }
#M_draw        = { git = "https://github.com/urbanjost/M_draw.git" }
