# TOML file for fpm as described at https://github.com/fortran-lang/fpm/blob/master/manifest-reference.md
name = "M_draw"
version = "1.0.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John S. Urban"
description = "basic vector graphics package"
categories = ["graphics"]
keywords = ["fortran", "draw", "plot", "graphics"]
homepage = "https://github.com/urbanjost/M_draw.git"
[build]
auto-executables = true  # Toggle automatic discovery of executables
auto-examples = true     # Toggle automatic discovery of example programs
auto-tests = true        # Toggle automatic discovery of test executables
link = ["X11"]           # Linking against libraries

[library]
source-dir = "src"

[[executable]]
name="make_hershey"
source-dir="app/make_hershey"
main="make_hershey.f90"

[[executable]]
name="h2v"
source-dir="app/MAKE_HERSHEY"
main="h2v.c"
