# TOML file for fpm as described at https://fpm.fortran-lang.org/en/spec/manifest.html
name = "M_draw"
version = "0.1.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John S. Urban"
description = "basic vector graphics package"

[library]
source-dir = "src"
build-script = "fpm.mk"

[[test]]
name="make_hershey"
source-dir="test/make_hershey"
main="make_hershey.f90"

[[executable]]
name="h2v"
source-dir="PROGRAMS/MAKE_HERSHEY"
main="h2v.c"
