system on
pg 999999999999
# the size of a font is normalized based on the widest character
# so putting a big character into a font set can make the other
# characters be drawn small
parcel edit
#ccall seedata.f 
#seedata < ../data/hersh.oc
#seedata < ../data/hersh.or
vi ../fonts/marker2.hmp
h2v ../data/hersh.oc ../fonts/marker2.hmp $M_DRAW_FONTPATH/markers 
post

parcel pp
font markers
move2 0 ystart
set $A=$char(ichars,ichars,ichars,ichars,ichars,ichars)
set $A=$str($A,$A)
drawstr $A
set ichars=ichars+1
set ystart=ystart-1
post

textsize 1 1
sz 200 1000 
page 0 20 0 ystart=100
set ichars=33
x edit
x pp DO=100-7
set $q("enter something")
page 0; sz 1000
#seefont markers
#set $q("enter something")
font futura.m
id -n 1
id
